### ISSUE TITLE
Global markers won't work

### ISSUE THREAD

**Issue by thanhvg** [xueeinstein/helm-evil-markers#1]
This is wonderful package. However it won't work with global markers (those that are marked with capital letters (A-Z) should be accessible across buffers). 

 Also I have problem with stale marker list, but it could be due to my emacs config.

Thanks

**Comment by xueeinstein** [comment]
@thanhvg Currently, this package doesn't support global markers. I may support it in the future version. 

How to reproduce the stale marker list? Can you describe it in details? Normally, this package tracks the buffer name, modification tick, `m-*`, etc, to update markers list.

**Comment by thanhvg** [comment]
As I said it could be due to my config as I use `Spacemacs` so don't bother it.

But imo you shouldn't need such a clever way to track marker list. A straight marker list getter would be just fine like the builtin `evil-show-marks`

**Comment by xueeinstein** [comment]
The built-in evil helper works. But it doesn't give you any hints about the markers. That's what this package aims for.

**Comment by xueeinstein** [comment]
`helm-evil-markers` supports global markers now. So I closed this issue.

![Screenshot from 2019-07-19 13-45-27](https://user-images.githubusercontent.com/3424201/61512127-87ca2b80-aa2b-11e9-9bc5-65e6fa08f9f6.png)
